// server.js
const express = require('express');
const axios = require('axios');
const cors = require('cors');
const fs = require('fs').promises;
const path = require('path');
require('dotenv').config();
const nodemailer = require('nodemailer');

const app = express();
const port = process.env.SERVERPORT || 5000;
console.log('Server port:', port);

// Middleware
app.use(cors({
    origin: '*', // Allow all origins
    methods: ['GET', 'POST', 'OPTIONS'],
    allowedHeaders: ['Content-Type', 'Authorization'],
    credentials: true
}));
app.use(express.json());

// Error handling middleware
app.use((err, req, res, next) => {
    console.error(err.stack);
    res.status(500).json({ error: 'Something went wrong!' });
});

const MAX_TOKENS = 600;
const OPENAI_API_KEY = process.env.OPENAI_API_KEY;
const OPENAI_API_URL = 'https://api.openai.com/v1/chat/completions';
const DATA_FILE = path.join(__dirname, 'data.json');
const GOOGLE_API_KEY = process.env.GOOGLE_API_KEY;
const GOOGLE_CSE_ID = process.env.GOOGLE_CSE_ID;

// Create a transporter object using easyname.com SMTP
const transporter = nodemailer.createTransport({
    host: process.env.EMAIL_HOST,
    port: Number(process.env.EMAIL_PORT), // Ensure port is a number
    secure: process.env.EMAIL_SECURE === 'true', // Ensure secure is a boolean
    auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASSWORD
    },
    tls: {
        // Do not fail on invalid certs
        rejectUnauthorized: false
    }
});

// Function to generate email HTML content
function generateEmailContent(product, recommendation, searchResults) {
    console.log('Generating email content with:', {
        product,
        recommendationLength: recommendation.length,
        searchResultsCount: searchResults ? searchResults.length : 0,
        searchResults: searchResults
    });

    // Convert markdown to HTML
    const recommendationHtml = recommendation
        .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>') // Bold text
        .replace(/\n/g, '<br>') // Line breaks
        .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>') // Bold text again for nested cases
        .replace(/\*(.*?)\*/g, '<em>$1</em>') // Italic text
        .replace(/\[(.*?)\]\((.*?)\)/g, '<a href="$2" style="color: #2563eb;">$1</a>'); // Links

    const emailContent = `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
            <h1 style="color: #2563eb;">Review Cruncher Report</h1>
            <h2 style="color: #1e293b;">${product}</h2>
            <div style="margin: 20px 0; padding: 20px; background: #f8fafc; border-radius: 8px;">
                ${recommendationHtml}
            </div>
            <p style="color: #64748b; font-size: 14px; margin-top: 30px;">
                This email was generated by Review Cruncher. For more information, visit our website.
            </p>
        </div>
    `;

    console.log('Generated email content length:', emailContent.length);
    return emailContent;
}

// Function to read the data file
async function readDataFile() {
    try {
        const data = await fs.readFile(DATA_FILE, 'utf8');
        return JSON.parse(data);
    } catch (error) {
        // If file doesn't exist or is empty, return default structure
        return { reviews: [] };
    }
}

// Function to write to the data file
async function writeDataFile(data) {
    await fs.writeFile(DATA_FILE, JSON.stringify(data, null, 2), 'utf8');
}

// Endpoint to handle product recommendations
app.post('/api/recommend', async (req, res) => {
    try {
        const { product, email, expectations } = req.body;

        if (!product || !email) {
            return res.status(400).json({ error: 'Product and email are required' });
        }

        const headers = {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + OPENAI_API_KEY
        };

        const params = {
            model: 'gpt-4.1',
            max_tokens: MAX_TOKENS,
            messages: [
                {
                    role: 'developer',
                    content:
                        'You are a recommendation expert specializing in products, services, and experiences. First, analyze the user\'s input to determine the type of request.\n\n' +
                        '1. If it\'s a specific product (e.g., "iPhone 14 Pro" or "Specialized Turbo Levo"):\n' +
                        '   - Identify the best-in-class alternative\n' +
                        '   - Provide a structured comparison as follows:\n\n' +
                        '**[Product Name] vs. [Best-in-Class Alternative]**\n\n' +
                        '**Key Features Comparison:**\n' +
                        '- [Product Name]:\n  * [Key Feature 1]\n  * [Key Feature 2]\n  * [Key Feature 3]\n' +
                        '- [Best-in-Class Alternative]:\n  * [Key Feature 1]\n  * [Key Feature 2]\n  * [Key Feature 3]\n\n' +
                        '**Advantages [Product Name]:**\n1. [First advantage]\n2. [Second advantage]\n3. [Third advantage]\n\n' +
                        '**Advantages [Best-in-Class Alternative]:**\n1. [First advantage]\n2. [Second advantage]\n3. [Third advantage]\n\n' +
                        '**Price Comparison:**\n[Product Name] is around [price] and [Best-in-Class Alternative] is around [price].\n\n' +
                        '**Value for Money Rating (1-5):**\n- [Product Name]: [Rating] - [Brief explanation]\n- [Best-in-Class Alternative]: [Rating] - [Brief explanation]\n\n' +
                        '**Recommendation:**\nMake a clear recommendation to buy or not. Decide for one of the products and give a clear recommendation.\n\n' +
                        '2. If it\'s a product category (e.g., "mountain bikes" or "batteries"):\n' +
                        '   - First identify the best-in-class product in that category\n' +
                        '   - Then identify the best value alternative\n' +
                        '   - Provide a structured comparison using the exact same format as above, but with:\n\n' +
                        '**[Best-in-Class Product] vs. [Best Value Alternative]**\n\n' +
                        '[Then follow the exact same structure as case 1, including Key Features Comparison, Advantages, Price Comparison, Value for Money Rating, and Recommendation]\n\n' +
                        '3. If the requested topic is about "travel destinations":\n' +
                        '   - Provide a structured recommendation as follows:\n\n' +
                        '**[Destination] Recommendations**\n\n' +
                        'Short summary about, what is the main reason, anybody would travel to that destination.\n\n' +
                        '**Top Touristic Picks - what to visit:**\n1. [First Recommendation]\n' +
                        '   - [Brief explanation]\n' +
                        '   - Key Highlights:\n' +
                        '     * [Highlight 1]\n' +
                        '     * [Highlight 2]\n' +
                        '     * [Highlight 3]\n\n' +
                        '2. [Second Recommendation]\n' +
                        '   - [Brief explanation]\n' +
                        '   - Key Highlights:\n' +
                        '     * [Highlight 1]\n' +
                        '     * [Highlight 2]\n' +
                        '     * [Highlight 3]\n\n' +
                        '3. [Third Recommendation]\n' +
                        '   - [Brief explanation]\n' +
                        '   - Key Highlights:\n' +
                        '     * [Highlight 1]\n' +
                        '     * [Highlight 2]\n' +
                        '     * [Highlight 3]\n\n' +
                        '**Considerations:**\n- [Important factor 1]\n- [Important factor 2]\n- [Important factor 3]\n\n' +
                        '**Hidden gem:**\n[A hint about an experience or location at the [Destination], which only a few people know.]\n\n' +
                        '4. For other non-product topics (e.g., "video games"):\n' +
                        '   - Provide a structured recommendation as follows:\n\n' +
                        '**[Topic] Recommendations**\n\n' +
                        '**Top Picks:**\n1. [First Recommendation]\n' +
                        '   - Why it\'s great: [Brief explanation]\n' +
                        '   - Best for: [type of user/experience]\n' +
                        '   - Key Highlights:\n' +
                        '     * [Highlight 1]\n' +
                        '     * [Highlight 2]\n' +
                        '     * [Highlight 3]\n\n' +
                        '2. [Second Recommendation]\n' +
                        '   - Why it\'s great: [Brief explanation]\n' +
                        '   - Best for: [type of user/experience]\n' +
                        '   - Key Highlights:\n' +
                        '     * [Highlight 1]\n' +
                        '     * [Highlight 2]\n' +
                        '     * [Highlight 3]\n\n' +
                        '**Considerations:**\n- [Important factor 1]\n- [Important factor 2]\n- [Important factor 3]\n\n' +
                        '**Recommendation:**\n[Clear recommendation based on the user\'s needs]\n\n' +
                        'Additional Guidelines:\n- If the input is not in English, answer in the language of the input text\n- Use markdown formatting with **bold** text for headers\n- Ensure proper line breaks and 1 empty line between sections\n- Limit the answer to 500 tokens while maintaining completeness\n- For product categories, focus on current market leaders and best value options\n- For travel destinations, follow the structure provided\n- For other non-product topics, focus on providing actionable, specific recommendations\n- If the user has provided specific expectations or requirements, make sure to address them in your recommendation and comparison\n\n' +
                        (expectations ? 'My expectations: ' + expectations + '\n\n' : '') +
                        'Hello. Shall I buy ' + product
                }
            ]
        };

        const response = await axios.post(OPENAI_API_URL, params, { headers });
        const firstChoice = response.data.choices[0];
        const responseData = {
            responseMessage: firstChoice.message.content,
            reason: firstChoice.finish_reason
        };

        // Save the request and response to data.json
        const data = await readDataFile();
        data.reviews.push({
            timestamp: new Date().toISOString(),
            product,
            email,
            expectations: expectations || '',
            response: responseData
        });
        await writeDataFile(data);

        res.json({ response: responseData });
    } catch (error) {
        console.error('Error:', error.response?.data || error.message);
        
        // Handle specific error cases
        if (error.response?.status === 401) {
            return res.status(401).json({ error: 'API key is invalid' });
        } else if (error.response?.status === 429) {
            return res.status(429).json({ error: 'Rate limit exceeded' });
        }
        
        res.status(500).json({ error: 'Something went wrong with the request' });
    }
});

// Google Search endpoint
app.post('/api/search', async (req, res) => {
    try {
        const { query } = req.body;
        if (!query) {
            return res.status(400).json({ error: 'Query is required' });
        }
        const url = 'https://www.googleapis.com/customsearch/v1?q=' + encodeURIComponent(query) + '&key=' + GOOGLE_API_KEY + '&cx=' + GOOGLE_CSE_ID;
        const response = await axios.get(url);

        // You can customize what you return to the frontend
        // Here, we return the top 5 results with title, link, and snippet
        const results = (response.data.items || []).slice(0, 5).map(item => ({
            title: item.title,
            link: item.link,
            snippet: item.snippet
        }));

        res.json({ results });
    } catch (error) {
        console.error('Google Search Error:', error.response?.data || error.message);
        res.status(500).json({ error: 'Google Search failed' });
    }
});

// Combined endpoint for both recommendation and search
app.post('/api/combined', async (req, res) => {
    try {
        const { product, email, expectations } = req.body;

        if (!product || !email) {
            return res.status(400).json({ error: 'Product and email are required' });
        }

        // Make both API calls in parallel
        const [recommendationResponse, searchResponse] = await Promise.all([
            // Recommendation API call
            axios.post(OPENAI_API_URL, {
                model: 'gpt-4.1',
                max_tokens: MAX_TOKENS,
                messages: [
                    {
                        role: 'developer',
                        content:
                            'You are a recommendation expert specializing in products, services, and experiences.' +
                            'First, analyze the user\'s input to determine the type of request.\n\n' +
                            '1. If it\'s a specific product (e.g., "iPhone 14 Pro" or "Specialized Turbo Levo"):\n' +
                            '   - Identify the best-in-class alternative\n' +
                            '   - Provide a structured comparison as follows:\n\n' +
                            '**[Product Name] key features**\n\n' +
                            '* [Key Feature 1]\n  * [Key Feature 2]\n  * [Key Feature 3]\n' +
                            '**You can consider [Best-in-Class Alternative] as an alternative**\n\n' +
                            '* [Key Feature 1]\n  * [Key Feature 2]\n  * [Key Feature 3]\n\n' +
                            '**Price Comparison:**\n[Product Name] is around [price] and [Best-in-Class Alternative] is around [price].\n\n' +
                            '**Value for Money Rating (1-5):**\n- [Product Name]: [Rating] - [Brief explanation]\n- [Best-in-Class Alternative]: [Rating] - [Brief explanation]\n\n' +
                            '**Recommendation:**\nMake a clear recommendation to buy or not. Decide for one of the products and give a clear recommendation. If the user provided expectations, make sure to address them in your recommendation.\n\n' +
                            '2. If it\'s a product category (e.g., "mountain bikes" or "batteries"):\n' +
                            '   - First identify the best-in-class product in that category. That will be our [Best-in-Class Product] for the comparision we will show to the User\n' +
                            '   - Then identify the best value alternative. That will be our [Best-Value Alternative] for the comparision\n' +
                            '   - Provide a structured comparison between [Best-in-Class Product] and [Best-Value Alternative] using the exact same format as above\n\n' +
                            '   - We will not evaluate the product category, we will only evaluate the [Best-in-Class Product] and [Best-Value Alternative] and give a recommendation to the User\n\n' +
                            '**[Best-in-Class Product name] key features**\n\n' +
                            '* [Key Feature 1]\n  * [Key Feature 2]\n  * [Key Feature 3]\n' +
                            '**You can consider [Best-Value Alternative name] as an alternative**\n\n' +
                            '* [Key Feature 1]\n  * [Key Feature 2]\n  * [Key Feature 3]\n\n' +
                            '[Then follow the exact same structure as case 1, including Price Comparison, Value for Money Rating, and Recommendation]\n\n' +
                            'Additional Guidelines:\n- If the input is not in English, answer in the language of the input text\n' +
                            '- Use markdown formatting with **bold** text for headers\n' +
                            '- Ensure proper line breaks and 1 empty line before bold text headers\n' +
                            '- Limit the answer to 500 tokens while maintaining completeness\n' +
                            '- For product categories, focus on current market leaders and best value options\n' +
                            '- For travel destinations, follow the structure provided\n' +
                            '- For other non-product topics, focus on providing actionable, specific recommendations\n' +
                            '- If the user has provided specific expectations or requirements, make sure to address them in your recommendation and comparison\n\n' +
                            'Hello. Shall I buy ' + product + ', or do I have a better option? ' + (expectations ? '\n\nMy expectations: ' + expectations : '')
                    },
                    {
                        role: 'user',
                        content: 'Hello. Shall I buy ' + product + ', or do I have a better option? ' + (expectations ? '\n\nMy expectations: ' + expectations : '')
                    }
                ]
            }, {
                headers: {
                    'Content-Type': 'application/json',
                    'Authorization': 'Bearer ' + OPENAI_API_KEY
                }
            }),
            // Google Search API call
            axios.get('https://www.googleapis.com/customsearch/v1?q=' + encodeURIComponent(product + ' Youtube review') + '&key=' + GOOGLE_API_KEY + '&cx=' + GOOGLE_CSE_ID)
        ]);

        const recommendationData = {
            responseMessage: recommendationResponse.data.choices[0].message.content + '\n\n\n**Youtube reviews**\n\n' + 
                (searchResponse.data.items || [])
                    .slice(0, 5)
                    .map((item, index) => `${index + 1}. [${item.title}](${item.link})`)
                    .join('\n'),
            reason: recommendationResponse.data.choices[0].finish_reason
        };

        const searchResults = (searchResponse.data.items || []).slice(0, 5).map(item => ({
            title: item.title,
            link: item.link,
            snippet: item.snippet
        }));

        // Save both results to data.json
        const data = await readDataFile();
        data.reviews.push({
            timestamp: new Date().toISOString(),
            product,
            email,
            expectations: expectations || '',
            recommendation: recommendationData,
            searchResults
        });
        await writeDataFile(data);

        res.json({
            recommendation: recommendationData,
            search: searchResults
        });
    } catch (error) {
        console.error('Error:', error.response?.data || error.message);
        res.status(500).json({ error: 'Something went wrong with the request' });
    }
});

// Endpoint to send email
app.post('/api/send-email', async (req, res) => {
    try {
        console.log('Raw request body:', req.body);
        
        const { product, email, recommendation, search_results } = req.body;

        console.log('Parsed request data:', {
            product,
            email,
            recommendationLength: recommendation ? recommendation.length : 0,
            searchResultsCount: search_results ? search_results.length : 0,
            searchResults: search_results
        });

        if (!product || !email || !recommendation) {
            console.error('Missing required fields:', { product, email, recommendation: !!recommendation });
            return res.status(400).json({ error: 'Missing required fields' });
        }

        const mailOptions = {
            from: process.env.EMAIL_USER,
            to: email,
            subject: 'Review Cruncher Report: ' + product,
            html: generateEmailContent(product, recommendation, search_results || [])
        };

        console.log('Sending email with options:', {
            from: mailOptions.from,
            to: mailOptions.to,
            subject: mailOptions.subject,
            searchResultsCount: search_results ? search_results.length : 0
        });

        const info = await transporter.sendMail(mailOptions);
        console.log('Email sent successfully:', info.messageId);
        
        res.json({ success: true, message: 'Email sent successfully' });
    } catch (error) {
        console.error('Email error:', error);
        res.status(500).json({ error: 'Failed to send email' });
    }
});

// Endpoint to get recent reviews
app.get('/api/recent-reviews', async (req, res) => {
    try {
        const data = await readDataFile();
        // Sort by timestamp descending and get last 4
        const sorted = (data.reviews || []).sort((a, b) => new Date(b.timestamp) - new Date(a.timestamp));
        const last4 = sorted.slice(0, 4);
        res.json({ reviews: last4 });
    } catch (error) {
        console.error('Error fetching recent reviews:', error);
        res.status(500).json({ error: 'Failed to fetch recent reviews' });
    }
});

// Start the server
app.listen(port, () => {
    console.log(`Server running on port ${port}`);
});
